# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\y.morozov\Repos\pose_estimator\manual_positioning\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.VerticalLayout_Image = QtWidgets.QVBoxLayout()
        self.VerticalLayout_Image.setObjectName("VerticalLayout_Image")
        self.horizontalLayout_2.addLayout(self.VerticalLayout_Image)
        self.VerticalLayout_Controls = QtWidgets.QVBoxLayout()
        self.VerticalLayout_Controls.setObjectName("VerticalLayout_Controls")
        self.ControlsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ControlsBox.setMinimumSize(QtCore.QSize(200, 0))
        self.ControlsBox.setTitle("")
        self.ControlsBox.setObjectName("ControlsBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.ControlsBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.ControlsBox)
        self.label.setMinimumSize(QtCore.QSize(0, 100))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.ModelsBox = QtWidgets.QGroupBox(self.ControlsBox)
        self.ModelsBox.setMinimumSize(QtCore.QSize(0, 400))
        self.ModelsBox.setMaximumSize(QtCore.QSize(16777215, 400))
        self.ModelsBox.setObjectName("ModelsBox")
        self.radioButton_Human1 = QtWidgets.QRadioButton(self.ModelsBox)
        self.radioButton_Human1.setGeometry(QtCore.QRect(20, 50, 16, 17))
        self.radioButton_Human1.setText("")
        self.radioButton_Human1.setChecked(True)
        self.radioButton_Human1.setObjectName("radioButton_Human1")
        self.radioButton_Human2 = QtWidgets.QRadioButton(self.ModelsBox)
        self.radioButton_Human2.setGeometry(QtCore.QRect(20, 140, 16, 17))
        self.radioButton_Human2.setText("")
        self.radioButton_Human2.setObjectName("radioButton_Human2")
        self.label_1 = QtWidgets.QLabel(self.ModelsBox)
        self.label_1.setGeometry(QtCore.QRect(50, 30, 121, 61))
        self.label_1.setText("")
        self.label_1.setPixmap(QtGui.QPixmap("resources/human1.png"))
        self.label_1.setScaledContents(True)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.ModelsBox)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 46, 13))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.ModelsBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.NextButton = QtWidgets.QPushButton(self.ControlsBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NextButton.sizePolicy().hasHeightForWidth())
        self.NextButton.setSizePolicy(sizePolicy)
        self.NextButton.setMinimumSize(QtCore.QSize(0, 50))
        self.NextButton.setObjectName("NextButton")
        self.verticalLayout_5.addWidget(self.NextButton)
        self.VerticalLayout_Controls.addWidget(self.ControlsBox)
        self.horizontalLayout_2.addLayout(self.VerticalLayout_Controls)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuModel = QtWidgets.QMenu(self.menubar)
        self.menuModel.setObjectName("menuModel")
        self.menuSelect = QtWidgets.QMenu(self.menuModel)
        self.menuSelect.setObjectName("menuSelect")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSelect_Folder = QtWidgets.QAction(MainWindow)
        self.actionSelect_Folder.setObjectName("actionSelect_Folder")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHuman1 = QtWidgets.QAction(MainWindow)
        self.actionHuman1.setObjectName("actionHuman1")
        self.actionHuman2 = QtWidgets.QAction(MainWindow)
        self.actionHuman2.setObjectName("actionHuman2")
        self.actionFit_image = QtWidgets.QAction(MainWindow)
        self.actionFit_image.setObjectName("actionFit_image")
        self.actionSelect_File = QtWidgets.QAction(MainWindow)
        self.actionSelect_File.setObjectName("actionSelect_File")
        self.menuFile.addAction(self.actionSelect_File)
        self.menuFile.addAction(self.actionSelect_Folder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSelect.addAction(self.actionHuman1)
        self.menuSelect.addAction(self.actionHuman2)
        self.menuModel.addAction(self.menuSelect.menuAction())
        self.menuView.addAction(self.actionFit_image)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuModel.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.ModelsBox.setTitle(_translate("MainWindow", "Models"))
        self.NextButton.setText(_translate("MainWindow", "Next>>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuModel.setTitle(_translate("MainWindow", "Model"))
        self.menuSelect.setTitle(_translate("MainWindow", "Select"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionSelect_Folder.setText(_translate("MainWindow", "Select Folder..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionHuman1.setText(_translate("MainWindow", "Human1"))
        self.actionHuman2.setText(_translate("MainWindow", "Human2"))
        self.actionFit_image.setText(_translate("MainWindow", "Fit image"))
        self.actionSelect_File.setText(_translate("MainWindow", "Select File..."))

